version: "3.8"

services:
  chatwoot_app:
    image: chatwoot/chatwoot:latest
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    #command: bundle exec rails db:chatwoot_prepare
    entrypoint: docker/entrypoints/rails.sh
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - traefik_public
    environment:
      INSTALLATION_NAME: dualtec
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: m7qa33g51uzeiew5vsjqb4av
      FRONTEND_URL: https://seu.site.com.br
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      REDIS_URL: redis://redis:6379
      # Banco de dados
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mudar@mudar
      POSTGRES_DATABASE: chatwoot
      # Armazenamento
      ACTIVE_STORAGE_SERVICE: local
      # logs
      RAILS_LOG_TO_STDOUT: "true"
      # Avatar Bot
      USE_INBOX_AVATAR_FOR_BOT: "true"
      #performance
      SIDEKIQ_CONCURRENCY: 10
      RACK_TIMEOUT_SERVICE_TIMEOUT: 0
      #- RAILS_MAX_THREADS=5
      #- WEB_CONCURRENCY=2
      ENABLE_RACK_ATTACK: "false"
      TZ: America/Campo_Grande
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.chatwoot_app.rule=Host(`seu.site.com.br`)
        - traefik.http.routers.chatwoot_app.entrypoints=websecure
        - traefik.http.routers.chatwoot_app.tls.certresolver=le
        - traefik.http.routers.chatwoot_app.service=chatwoot_app
        - traefik.http.services.chatwoot_app.loadbalancer.server.port=3000
        - traefik.http.middlewares.chatwoot_sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.chatwoot_app.middlewares=chatwoot_sslheader

  #worker (Trabalhador que executa os processos)
  chatwoot_worker:
    image: chatwoot/chatwoot:latest
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - chatwoot_data:/app/storage
    networks:
      - traefik_public
    environment:
      INSTALLATION_NAME: dualtec
      NODE_ENV: production
      RAILS_ENV: production
      INSTALLATION_ENV: docker
      SECRET_KEY_BASE: m7qa33g51uzeiew5vsjqb4av
      FRONTEND_URL: https://seu.site.com.br
      DEFAULT_LOCALE: pt_BR
      FORCE_SSL: "true"
      ENABLE_ACCOUNT_SIGNUP: "false"
      REDIS_URL: redis://redis:6379
      # Banco de dados
      POSTGRES_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: mudar@mudar
      POSTGRES_DATABASE: chatwoot
      # Armazenamento
      ACTIVE_STORAGE_SERVICE: local
      # logs
      RAILS_LOG_TO_STDOUT: "true"
      # Avatar Bot
      USE_INBOX_AVATAR_FOR_BOT: "true"
      #performance
      SIDEKIQ_CONCURRENCY: 10
      RACK_TIMEOUT_SERVICE_TIMEOUT: 0
      #- RAILS_MAX_THREADS=5
      #- WEB_CONCURRENCY=2
      ENABLE_RACK_ATTACK: "false"
      TZ: America/Campo_Grande
      #Mesmas VARIAVEIS do Chatwoot App
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.5"
          memory: 1024M

volumes:
  chatwoot_data:
    external: true

networks:
  traefik_public:
    external: true
 